-- MySQL Script generated by MySQL Workbench
-- Sun Sep 18 22:50:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema z01dyw55x7evichz
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `z01dyw55x7evichz` ;

-- -----------------------------------------------------
-- Schema z01dyw55x7evichz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `z01dyw55x7evichz` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `z01dyw55x7evichz` ;

-- -----------------------------------------------------
-- Table `z01dyw55x7evichz`.`found`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `z01dyw55x7evichz`.`found` ;

CREATE TABLE IF NOT EXISTS `z01dyw55x7evichz`.`found` (
  `pet_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `gender` VARCHAR(50) NOT NULL,
  `age` VARCHAR(50) NULL,
  `species` VARCHAR(50) NOT NULL,
  `photo` VARBINARY(20) NULL,
  `date` VARCHAR(50) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_userscredentials_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_userscredentials_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `z01dyw55x7evichz`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `z01dyw55x7evichz`.`lost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `z01dyw55x7evichz`.`lost` ;

CREATE TABLE IF NOT EXISTS `z01dyw55x7evichz`.`lost` (
  `pet_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `gender` VARCHAR(50) NOT NULL,
  `age` VARCHAR(50) NULL,
  `species` VARCHAR(50) NOT NULL,
  `photo` VARBINARY(20) NULL,
  `date` VARCHAR(50) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_userscredentials_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_userscredentials_users11`
    FOREIGN KEY (`users_id`)
    REFERENCES `z01dyw55x7evichz`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `z01dyw55x7evichz`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `z01dyw55x7evichz`.`users` ;

CREATE TABLE IF NOT EXISTS `z01dyw55x7evichz`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `z01dyw55x7evichz`.`usersCredentials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `z01dyw55x7evichz`.`usersCredentials` ;

CREATE TABLE IF NOT EXISTS `z01dyw55x7evichz`.`usersCredentials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  INDEX `fk_userscredentials_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_userscredentials_users10`
    FOREIGN KEY (`users_id`)
    REFERENCES `z01dyw55x7evichz`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
